src/main/java/cz/kaceni/website/model/PriceOffer.java
package cz.kaceni.website.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Version;
import javax.validation.Valid;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Email;
import org.joda.time.DateTime;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.util.Assert;

import cz.devmint.springext.constants.TypeDefsNames;
import cz.devmint.springext.orm.hibernate.IdGenerator;
import cz.devmint.springext.validation.validator.ValidatorConstants;
import cz.kaceni.website.model.embedded.Address;
import cz.kaceni.website.model.util.LengthConstraints;

/**
 * Entity representing price offer for given inquiry.
 * 
 * @author Pavla Novakova [pavla.novakova(at)gmail.com]
 */
@Entity
public class PriceOffer implements Serializable {

	@Id
	@GeneratedValue(generator = IdGenerator.GENERATOR_TABLE_NOOP_NAME)
	@Access(AccessType.PROPERTY)
	private Long id;

	@Version
	@Column(nullable = false)
	private Long version;

	@OneToOne(fetch = FetchType.LAZY, optional=true)
	private Inquiry inquiry;
	
	/** Customer address that is part of price offer header. Default value is taken from inquiry address. */
	@Embedded
	@Valid
	private Address address = new Address();
	
	/** Customer phone number that is part of price offer header. Default value is taken from inquiry phone number. */
	@Size(max = LengthConstraints.CUSTOMER_PHONE_NUMBER)
	private String phoneNumber;
	
	/** Customer email that is part of price offer header. Default value is taken from inquiry email. */
	@Email
	@Size(max = ValidatorConstants.EMAIL_LENGTH)
	private String email;
		
	@OneToMany(fetch = FetchType.LAZY, mappedBy="priceOffer", cascade=CascadeType.REMOVE)
	@Valid
	private List<PriceOfferItem> priceOfferItemList;
	
	/** Note that may be printed in price offer for internal purposes (not visible to customer) */
	@Size(max=500)
	private String internalNote;

	@Column(nullable = false)
	private BigDecimal totalPriceWithoutVat = BigDecimal.ZERO;

	@Column(nullable = false)	
	private BigDecimal totalPriceWithVat = BigDecimal.ZERO;
	
	@Type(type=TypeDefsNames.JODA_DATE_TIME)
	@DateTimeFormat(pattern="dd.MM.yyyy")
	private DateTime date;

	public void calculatePrice() {
		totalPriceWithoutVat = BigDecimal.ZERO;
		totalPriceWithVat = BigDecimal.ZERO;
		for (PriceOfferItem priceOfferItem : priceOfferItemList) {
			totalPriceWithoutVat = totalPriceWithoutVat.add(priceOfferItem.getPriceWithoutVat());
			totalPriceWithVat = totalPriceWithVat.add(priceOfferItem.getPriceWithVat());
		}
	}
	
	public BigDecimal getTotalVat() {
		return totalPriceWithVat.subtract(totalPriceWithoutVat);
	}
	
	public BigDecimal getTotalPriceChipping() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceChipping() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceChipping()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceDisposal() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceDisposal() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceDisposal()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceTrimming() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceTrimming() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceTrimming()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceFelling() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceFelling() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceFelling()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceStumpsMilling() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceStumpsMilling() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceStumpsMilling()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceBinding() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceBinding() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceBinding()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceOther() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceOther() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceOther()));
			}
		}
		return total;
	}
	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Inquiry getInquiry() {
		return inquiry;
	}

	public void setInquiry(Inquiry inquiry) {
		this.inquiry = inquiry;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getInternalNote() {
		return internalNote;
	}

	public void setInternalNote(String internalNote) {
		this.internalNote = internalNote;
	}

	public DateTime getDate() {
		return date;
	}

	public void setDate(DateTime date) {
		this.date = date;
	}

	public List<PriceOfferItem> getPriceOfferItemList() {
		return priceOfferItemList;
	}

	public void setPriceOfferItemList(List<PriceOfferItem> priceOfferItemList) {
		this.priceOfferItemList = priceOfferItemList;
	}

	public BigDecimal getTotalPriceWithoutVat() {
		return totalPriceWithoutVat;
	}

	public void setTotalPriceWithoutVat(BigDecimal totalPriceWithoutVat) {
		this.totalPriceWithoutVat = totalPriceWithoutVat;
	}

	public BigDecimal getTotalPriceWithVat() {
		return totalPriceWithVat;
	}

	public void setTotalPriceWithVat(BigDecimal totalPriceWithVat) {
		this.totalPriceWithVat = totalPriceWithVat;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		PriceOffer other = (PriceOffer) obj;
		if (id == null) {
			if (other.id != null) return false;
		} else if (!id.equals(other.id)) return false;
		return true;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PriceOffer [id=");
		builder.append(id);
		builder.append(", version=");
		builder.append(version);
		builder.append(", inquiry=");
		builder.append(inquiry);
		builder.append(", address=");
		builder.append(address);
		builder.append(", phoneNumber=");
		builder.append(phoneNumber);
		builder.append(", email=");
		builder.append(email);
		builder.append(", priceOfferItemList=");
		builder.append(priceOfferItemList);
		builder.append(", internalNote=");
		builder.append(internalNote);
		builder.append(", totalPriceWithoutVat=");
		builder.append(totalPriceWithoutVat);
		builder.append(", totalPriceWithVat=");
		builder.append(totalPriceWithVat);
		builder.append(", date=");
		builder.append(date);
		builder.append("]");
		return builder.toString();
	}
	
	

}

src/main/webapp/WEB-INF/jsp/_include/formPartOtherType.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/_include/taglibs.jsp" %>
<fieldset id="${param.workType}" class="theme-indent collapse">
   	<div class="form-group">
   		<spring-ext:label path="workList[${param.index}].numberOfItems" cssClass="control-label col-sm-2"/>
   		<div class="col-sm-2">
   			<spring-ext:input path="workList[${param.index}].numberOfItems" cssClass="form-control"/>
   		</div>
   		<c:if test="${param.workType == 'MULTIPLE_FELLING' || param.workType == 'MULTIPLE_RISK_FELLING'}">
	   		<spring-ext:label path="workList[${param.index}].additionalNumberOfItems" cssClass="control-label col-sm-2"/>
	   		<div class="col-sm-2">
	   			<spring-ext:input path="workList[${param.index}].additionalNumberOfItems" cssClass="form-control" />
	   		</div>
   		</c:if>
   		<c:if test="${param.workType == 'MILLING_OF_STUMPS'}">
   			<spring-ext:label path="workList[${param.index}].diameter" cssClass="control-label col-sm-2"/>
	   		<div class="col-sm-2">
	   			<spring-ext:input path="workList[${param.index}].diameter" cssClass="form-control" forceHelp="true" />
	   		</div>
   		</c:if>
	</div>
	<c:if test="${param.workType != 'PLANTING'}">
		<div class="form-group">
			<div class="col-sm-12">
				<p class="form-actions">
					<a href="#upload-photo" class="btn btn-default btn-sm" data-imageFolderId-path="workList[${param.index}].imageFolderId" data-photoList-path="workList[${param.index}].photoList" data-target-type="${param.workType}" >Nahrát fotografii (max 5)</a>
					<form:hidden path="workList[${param.index}].imageFolderId" />
					<form:hidden path="workList[${param.index}].photoList" />
					<a href="#gps-location" data-toggle="modal" data-target-path="workList[${param.index}].gpsLocation" class="btn btn-default btn-sm">Označit na Google Mapě </a>
					<form:hidden path="workList[${param.index}].gpsLocation" />
				</p>
			</div>
			<div class="col-sm-12">
				<div id="uploaded-photos-${param.workType}" class="img-container">
					<c:if test="${!empty inquiry.workList[param.index].photoList}">
						<c:forEach items="${inquiry.workList[param.index].photoList}" var="photo">
							<p>
								<span class="img" style="background-image: url('${photo.thumbnailLink}')"></span>
								<a href="#remove-img" data-file-id="${photo.id}" title="Smazat fotografii">
									<i class='glyphicon glyphicon-trash'><span>Smazat fotografii</span></i> ${photo.originalFilename}
								</a>
							</p>
						</c:forEach>
					</c:if>
				</div>
			</div>
		</div>
	</c:if>
</fieldset>					

src/main/webapp/WEB-INF/jsp/_include/formPartSingleTreeFelling.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/_include/taglibs.jsp" %>
<fieldset id="${param.workType}" class="theme-indent collapse" data-path="workList[${param.index}]">
   	<div class="form-group">
   		<div class="col-lg-3 col-md-4 col-sm-5"><p><img src="<c:url value='/resources/imgs/strom.gif' />" alt="Rozměry stromu" class="img-responsive" /></p></div>
   		<div class="col-lg-4 col-md-5 col-sm-6">
    		<div class="row">
		    	<spring-ext:label path="workList[${param.index}].height" cssClass="control-label col-md-4 col-sm-5 col-xs-12"/>
		    	<div class="col-sm-6 col-md-5 col-xs-6">
		    		<p><spring-ext:inputGroup path="workList[${param.index}].height" cssClass="form-control" suffix="m" /></p>
				</div>
			</div>
			<div class="row">
				<spring-ext:label path="workList[${param.index}].girth" cssClass="control-label col-md-4 col-sm-5 col-xs-12"/>
				<div class="col-sm-6 col-md-5 col-xs-6">
					<p><spring-ext:inputGroup path="workList[${param.index}].girth" cssClass="form-control" suffix="cm" /></p>	
				</div>
			</div>
			<div class="row">
				<spring-ext:label path="workList[${param.index}].crownWidth" cssClass="control-label col-md-4 col-sm-5 col-xs-12" />
				<div class="col-sm-6 col-md-5 col-xs-6">
					<p><spring-ext:inputGroup path="workList[${param.index}].crownWidth" cssClass="form-control" suffix="m" /></p>
				</div>
			</div>
			<div class="row">
				<spring-ext:label path="workList[${param.index}].treeType" cssClass="control-label col-md-4 col-sm-5 col-xs-12" />
				<div class="col-sm-6 col-md-5 col-xs-6">
					<p><spring-ext:input path="workList[${param.index}].treeType" cssClass="form-control"/></p>
				</div>
			</div>
		</div>
		<div class="clearfix visible-sm-block visible-md-block"></div>
		<div class="col-lg-5 col-md-6 col-sm-7 reset-col">
			<p><spring-ext:label path="workList[${param.index}].itemsDescription" /></p>	
		    <spring-ext:textarea path="workList[${param.index}].itemsDescription" cssClass="form-control" rows="8" />
		</div>	
	</div>
	<div class="form-group">
		<div class="col-sm-12">
			<p class="form-actions">
				<a href="#upload-photo" class="btn btn-default btn-sm" data-imageFolderId-path="workList[${param.index}].imageFolderId" data-photoList-path="workList[${param.index}].photoList" data-target-type="${param.workType}" >Nahrát fotografii (max 5)</a>
				<form:hidden path="workList[${param.index}].imageFolderId" />
				<form:hidden path="workList[${param.index}].photoList" />
				<a href="#gps-location" data-toggle="modal" data-target-path="workList[${param.index}].gpsLocation" class="btn btn-default btn-sm">Označit na Google Mapě </a>
				<form:hidden path="workList[${param.index}].gpsLocation" />
			</p>
		</div>
		<div class="col-sm-12">
			<div id="uploaded-photos-${param.workType}" class="img-container">
				<c:if test="${!empty inquiry.workList[param.index].photoList}">
					<c:forEach items="${inquiry.workList[param.index].photoList}" var="photo">
						<p>
							<span class="img" style="background-image: url('${photo.thumbnailLink}')"></span>
							<a href="#remove-img" data-file-id="${photo.id}" title="Smazat fotografii">
								<i class='glyphicon glyphicon-trash'><span>Smazat fotografii</span></i> ${photo.originalFilename}
							</a>
						</p>
					</c:forEach>
				</c:if>
			</div>
		</div>
	</div>
</fieldset>					

src/main/webapp/WEB-INF/jsp/_include/photoAndLocation.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/_include/taglibs.jsp" %>
<c:if test="${!empty work.gpsLocation}">
	<p><b>Poloha:</b> <a href="#gps-location" data-toggle="modal" data-location="${work.gpsLocation}">Zobrazit mapu</a></p>
</c:if>
<c:if test="${!empty work.photoList}">
	<div class="popup-gallery">
		<c:forEach items="${work.photoList}" var="photo">
			<a href="${photo.webContentLink}"><img src=" https://drive.google.com/thumbnail?sz=h220&id=${photo.id}" /></a>	
		</c:forEach>
	</div>
</c:if>

src/main/webapp/WEB-INF/jsp/_include/priceOfferTable.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/_include/taglibs.jsp" %>

<table class="table table-bordered">
<thead>
	<tr>
		<th>Název</th>
		<th>Mn.</th>
		<th>MJ</th>
		<th>Typ<br/>zásahu</th>
		<th>Cena<br/>štěpkování</th>
		<th>Cena<br/>likvidace<br/>dřeva</th>
		<th>Cena<br/>ořezu</th>
		<th>Cena<br/>kácení</th>
		<th>Cena<br/>frézování<br/>pařezu</th>
		<th>Cena<br/>vazby</th>
		<th>Cena<br/>ostatní</th>
		<th>Cena<br/>celkem<br/>bez DPH</th>
		<c:if test="${param.showVatRate}">
			<th>Sazba<br/>DPH</th>
		</c:if>
		<c:if test="${param.edit}">
			<th>&nbsp;</th>
			<th>&nbsp;</th>
		</c:if>
	</tr>
</thead>	
<tbody>								
	<c:forEach items="${priceOffer.priceOfferItemList}" var="priceOfferItem" varStatus="i">
		<tr>
			<td><c:out value="${priceOfferItem.name}" /></td>
			<td><f:formatNumber maxFractionDigits="2" value="${priceOfferItem.amount}"/></td>
			<td><c:out value="${priceOfferItem.amountUnit}" /></td>
			<td><c:out value="${priceOfferItem.type}" /></td>
			<td>
				<c:if test="${priceOfferItem.priceChipping.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOfferItem.priceChipping}"/>&nbsp;Kč
				</c:if>
			</td>
			<td>
				<c:if test="${priceOfferItem.priceDisposal.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOfferItem.priceDisposal}"/>&nbsp;Kč
				</c:if>	
			</td>
			<td>
				<c:if test="${priceOfferItem.priceTrimming.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOfferItem.priceTrimming}"/>&nbsp;Kč
				</c:if>	
			</td>
			<td>
				<c:if test="${priceOfferItem.priceFelling.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOfferItem.priceFelling}"/>&nbsp;Kč
				</c:if>	
			</td>
			<td>
				<c:if test="${priceOfferItem.priceStumpsMilling.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOfferItem.priceStumpsMilling}"/>&nbsp;Kč
				</c:if>	
			</td>
			<td>
				<c:if test="${priceOfferItem.priceBinding.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOfferItem.priceBinding}"/>&nbsp;Kč
				</c:if>	
			</td>
			<td>
				<c:if test="${priceOfferItem.priceOther.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOfferItem.priceOther}"/>&nbsp;Kč
				</c:if>	
			</td>
			<td>
				<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOfferItem.priceWithoutVat}"/>&nbsp;Kč
			</td>
			<c:if test="${param.showVatRate}">
				<td>
					<c:if test="${priceOfferItem.vatRate > 0}">
						<c:out value="${priceOfferItem.vatRate}" />&nbsp;%
					</c:if>
				</td>
			</c:if>
			<c:if test="${param.edit}">
				<td>
					<a href="<c:url value='/administrace/poptavky/detail-poptavky/${inquiryId}/uprava-polozky-cenove-nabidky/${priceOfferItem.id}' />" title="Upravit položku cenové nabídky" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-pencil"><span class="hidden">Upravit</span></i></a>
				</td>
				<td>
					<a href="<c:url value='/administrace/poptavky/detail-poptavky/${inquiryId}/smazat-polozku-cenove-nabidky/${priceOfferItem.id}' />" title="Smazat položku cenové nabídky" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-remove"><span class="hidden">Smazat</span></i></a>
				</td>
			</c:if>	
		</tr>
	</c:forEach>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="4">Celkem</td>
			<td>
				<c:if test="${priceOffer.totalPriceChipping.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceChipping}"/>&nbsp;Kč
				</c:if>
			</td>
			<td>
				<c:if test="${priceOffer.totalPriceDisposal.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceDisposal}"/>&nbsp;Kč
				</c:if>
			</td>
			<td>
				<c:if test="${priceOffer.totalPriceTrimming.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceTrimming}"/>&nbsp;Kč
				</c:if>
			</td>
			<td>
				<c:if test="${priceOffer.totalPriceFelling.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceFelling}"/>&nbsp;Kč
				</c:if>
			</td>
			<td>
				<c:if test="${priceOffer.totalPriceStumpsMilling.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceStumpsMilling}"/>&nbsp;Kč
				</c:if>
			</td>
			<td>
				<c:if test="${priceOffer.totalPriceBinding.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceBinding}"/>&nbsp;Kč
				</c:if>
			</td>
			<td>
				<c:if test="${priceOffer.totalPriceOther.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceOther}"/>&nbsp;Kč
				</c:if>
			</td>
			<td>
				<c:if test="${priceOffer.totalPriceWithoutVat.unscaledValue() != 0}">
					<f:formatNumber minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceWithoutVat}"/>&nbsp;Kč
				</c:if>
			</td>
			<c:if test="${param.showVatRate}">
				<td>&nbsp;</td>
			</c:if>
			<c:if test="${param.edit}">
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</c:if>
		</tr>
	</tfoot>
</table>	

src/main/webapp/WEB-INF/jsp/_include/servicesIndex.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/_include/taglibs.jsp" %>
<c:set var="serviceCols" value="col-sm-6 col-md-4" />
<div class="row theme-inverse" id="services-wrapper">
	<div class="${serviceCols}">
		<${param.h} id="odstranit">
			<a href="<c:url value='/sluzby/odstranit-strom' />" title="Kácení Šarapatka - odstranění stromu"><span></span></a>
			<a href="<c:url value='/sluzby/odstranit-strom' />" title="Kácení Šarapatka - odstranění stromu" class="link-text">Odstranit strom</a>
		</${param.h}>
	</div>
	<div class="${serviceCols}">
		<${param.h} id="vysadit">
			<a href="<c:url value='/sluzby/vysadit-strom' />" title="Kácení Šarapatka - vysazení stromu"><span></span></a>
			<a href="<c:url value='/sluzby/vysadit-strom' />" title="Kácení Šarapatka - vysazení stromu" class="link-text">Vysadit strom</a>
		</${param.h}>
	</div>
	<div class="${serviceCols}">
		<${param.h} id="orezat">
			<a href="<c:url value='/sluzby/orezat-strom' />" title="Kácení Šarapatka - ořez stromu"><span></span></a>
			<a href="<c:url value='/sluzby/orezat-strom' />" title="Kácení Šarapatka - ořez stromu" class="link-text">Ořezat strom</a>
		</${param.h}>
	</div>
	<div class="${serviceCols}">
		<${param.h} id="zabezpecit">
			<a href="<c:url value='/sluzby/zabezpecit-strom' />" title="Kácení Šarapatka - zabezpečení stromu"><span></span></a>
			<a href="<c:url value='/sluzby/zabezpecit-strom' />" title="Kácení Šarapatka - zabezpečení stromu" class="link-text">Zabezpečit strom</a>
		</${param.h}>
	</div>
	<div class="${serviceCols}">
		<${param.h} id="zhodnotit">
			<a href="<c:url value='/sluzby/zhodnotit-strom' />" title="Kácení Šarapatka - zhodnocení stromu"><span></span></a>
			<a href="<c:url value='/sluzby/zhodnotit-strom' />" title="Kácení Šarapatka - zhodnocení stromu" class="link-text">Zhodnotit strom</a>
		</${param.h}>
	</div>
	<div class="${serviceCols}">
		<${param.h} id="skoleni">
			<a href="<c:url value='/sluzby/skoleni-a-vzdelavani' />" title="Kácení Šarapatka - školení a vzdělávání"><span></span></a>
			<a href="<c:url value='/sluzby/skoleni-a-vzdelavani' />" title="Kácení Šarapatka - školení a vzdělávání" class="link-text">Školení a vzdělávání</a>
		</${param.h}>
	</div>
	<div class="${serviceCols}">
		<${param.h} id="frezovani">
			<a href="<c:url value='/sluzby/frezovani-parezu' />" title="Kácení Šarapatka - frézování pařezů"><span></span></a>
			<a href="<c:url value='/sluzby/frezovani-parezu' />" title="Kácení Šarapatka - frézování pařezů" class="link-text">Frézování pařezů</a>
		</${param.h}>
	</div>
</div>
	

src/main/webapp/WEB-INF/jsp/_include/taglibs.jsp
<%-- jstl taglibs --%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="f" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<%-- spring taglibs --%>
<%@taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@taglib prefix="spring-ext" uri="http://cz.devmint.spring-ext/tags" %>
<%@taglib prefix="spring-sec-ext" uri="http://cz.devmint.spring-ext/spring-security" %>
<%@taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<%-- spring security --%>
<%@taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>

<%-- tiles taglibs --%>
<%@taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>

<%-- joda taglib --%>
<%@taglib prefix="joda" uri="http://www.joda.org/joda/time/tags" %>

<%-- custom util taglibs --%>
<%@taglib prefix="ui" uri="http://cz.devmint.spring-ext/ui-tags" %>
<%@taglib prefix="asset" uri="http://cz.devmint.spring-ext/asset-tags" %>
<%@taglib prefix="pagination" uri="http://cz.devmint.spring-ext/pagination-tags" %>

<%@taglib prefix="app" tagdir="/WEB-INF/tags" %>
