src/main/java/cz/kaceni/website/dto/UploadForm.java
package cz.kaceni.website.dto;

import java.util.UUID;

import org.springframework.web.multipart.MultipartFile;

/**
 * Upload form inquiry / price offer import in admin section (file wrapper only). 
 * @author Pavla Novakova [pavla.novakova(at)gmail.com]
 */
public class UploadForm {
	
	private MultipartFile file;
	
	/** Optional - if set uploaded price offer is associated with existing inquiry.  */
	private UUID inquiryId;

	public UUID getInquiryId() {
		return inquiryId;
	}

	public void setInquiryId(UUID inquiryId) {
		this.inquiryId = inquiryId;
	}

	public MultipartFile getFile() {
		return file;
	}

	public void setFile(MultipartFile file) {
		this.file = file;
	}
	
}

src/main/java/cz/kaceni/website/model/Inquiry.java
package cz.kaceni.website.model;

import java.util.List;
import java.util.UUID;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Transient;
import javax.persistence.Version;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.annotations.Type;
import org.joda.time.DateTime;
import org.springframework.util.AutoPopulatingList;

import cz.devmint.springext.constants.TypeDefsNames;
import cz.devmint.springext.orm.hibernate.IdGenerator;
import cz.kaceni.website.model.embedded.Address;
import cz.kaceni.website.model.enums.InquiryStateEnum;
import cz.kaceni.website.model.enums.TermEnum;
import cz.kaceni.website.model.util.LengthConstraints;
import cz.kaceni.website.validation.groups.AdminInquiryChecks;

/**
 * Represents an inquiry (as filled by the customer)
 * 
 * @author Pavla Novakova [pavla.novakova(at)gmail.com]
 */
@Entity
public class Inquiry {

	public static final String NOT_SET_FIELD = "not.set@email.cz";
	
	@Id
	@GeneratedValue(generator = IdGenerator.ASSIGNED_GENERATOR_NAME)
	@Access(AccessType.PROPERTY)
	@Type(type="uuid-char")
	private UUID id;

	@Version
	@Column(nullable = false)
	private Long version;
	
	@ManyToOne(fetch = FetchType.EAGER, cascade={CascadeType.PERSIST, CascadeType.REMOVE})
	@JoinColumn(foreignKey = @ForeignKey(name = "inquiry_fk_customer"), nullable = false)
	@Valid
	private Customer customer = new Customer();

	/** Address of the place where the work is required. */
	@Embedded
	@Valid
	private Address address = new Address();
	
	@NotNull
	@Size(max = LengthConstraints.INQUIRY_MESSAGE)
	private String message;

	@Fetch(FetchMode.SUBSELECT)
	@OneToMany(mappedBy="inquiry")
	@Valid
	private List<Work> workList = new AutoPopulatingList<Work>(Work.class);

	/** selected work type list (checked checkboxes in inquiry form) */
	@ManyToMany(fetch = FetchType.LAZY)
	private List<WorkType> workTypeList = new AutoPopulatingList<WorkType>(WorkType.class);

	@Enumerated(EnumType.STRING)
	@Column(length=LengthConstraints.ENUM)
	private TermEnum term;

	private boolean requiresBill;

	private boolean vatPayer;
	
	@Size(max = 1000, groups=AdminInquiryChecks.class)
	@Column(length=1000)
	private String adminNote;
	
	@Enumerated(EnumType.STRING)
	@Column(length=LengthConstraints.ENUM)
	private InquiryStateEnum state = InquiryStateEnum.NEW;

	@Type(type=TypeDefsNames.JODA_DATE_TIME)
	@Column(nullable=false)
	private DateTime created;
	
	/** Google Drive id of image folder */
	@Column(length=50)
	private String imageFolderId;
	
	@Valid
	@Transient
	private PriceOffer priceOffer;
			
	public String getSubject() {
		StringBuilder subject = new StringBuilder("Požadované služby: ");
		for (Work work : workList) {
			subject.append(work.shortDescription());
			subject.append(" ;");
		}
		return subject.toString();
	}
	
	public String getAdminSubject() {
		StringBuilder subject = new StringBuilder();
		for (Work work : workList) {
			subject.append(work.shortDescription());
			subject.append("<br/>");
		}
		return subject.toString();
	}
	
	public Inquiry() {
		this.id = UUID.randomUUID();
	}

	public UUID getId() {
		return id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
	
	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public List<Work> getWorkList() {
		return workList;
	}

	public void setWorkList(List<Work> workList) {
		this.workList = workList;
	}

	public List<WorkType> getWorkTypeList() {
		return workTypeList;
	}

	public void setWorkTypeList(List<WorkType> workTypeList) {
		this.workTypeList = workTypeList;
	}

	public TermEnum getTerm() {
		return term;
	}

	public void setTerm(TermEnum term) {
		this.term = term;
	}

	public boolean isRequiresBill() {
		return requiresBill;
	}

	public void setRequiresBill(boolean requiresBill) {
		this.requiresBill = requiresBill;
	}

	public boolean isVatPayer() {
		return vatPayer;
	}

	public void setVatPayer(boolean vatPayer) {
		this.vatPayer = vatPayer;
	}

	public String getAdminNote() {
		return adminNote;
	}

	public void setAdminNote(String adminNote) {
		this.adminNote = adminNote;
	}

	public InquiryStateEnum getState() {
		return state;
	}

	public void setState(InquiryStateEnum state) {
		this.state = state;
	}

	public DateTime getCreated() {
		return created;
	}

	public void setCreated(DateTime created) {
		this.created = created;
	}

	public String getImageFolderId() {
		return imageFolderId;
	}

	public void setImageFolderId(String imageFolderId) {
		this.imageFolderId = imageFolderId;
	}

	public PriceOffer getPriceOffer() {
		return priceOffer;
	}

	public void setPriceOffer(PriceOffer priceOffer) {
		this.priceOffer = priceOffer;
	}

	/** Based on id, no suitable business key. */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/** Based on id, no suitable business key. */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		Inquiry other = (Inquiry) obj;
		if (id == null) {
			if (other.id != null) return false;
		} else if (!id.equals(other.id)) return false;
		return true;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Inquiry [id=");
		builder.append(id);
		builder.append(", version=");
		builder.append(version);
		builder.append(", customer=");
		builder.append(customer);
		builder.append(", address=");
		builder.append(address);
		builder.append(", message=");
		builder.append(message);
		builder.append(", workList=");
		builder.append(workList);
		builder.append(", workTypeList=");
		builder.append(workTypeList);
		builder.append(", term=");
		builder.append(term);
		builder.append(", requiresBill=");
		builder.append(requiresBill);
		builder.append(", vatPayer=");
		builder.append(vatPayer);
		builder.append(", adminNote=");
		builder.append(adminNote);
		builder.append(", state=");
		builder.append(state);
		builder.append(", created=");
		builder.append(created);
		builder.append(", imageFolderId=");
		builder.append(imageFolderId);
		builder.append("]");
		return builder.toString();
	}

}

src/main/java/cz/kaceni/website/model/PriceOffer.java
package cz.kaceni.website.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Version;
import javax.validation.Valid;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Type;
import org.hibernate.validator.constraints.Email;
import org.joda.time.DateTime;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.util.Assert;

import cz.devmint.springext.constants.TypeDefsNames;
import cz.devmint.springext.orm.hibernate.IdGenerator;
import cz.devmint.springext.validation.validator.ValidatorConstants;
import cz.kaceni.website.model.embedded.Address;
import cz.kaceni.website.model.util.LengthConstraints;

/**
 * Entity representing price offer for given inquiry.
 * 
 * @author Pavla Novakova [pavla.novakova(at)gmail.com]
 */
@Entity
public class PriceOffer implements Serializable {

	@Id
	@GeneratedValue(generator = IdGenerator.GENERATOR_TABLE_NOOP_NAME)
	@Access(AccessType.PROPERTY)
	private Long id;

	@Version
	@Column(nullable = false)
	private Long version;

	@OneToOne(fetch = FetchType.LAZY, optional=true)
	private Inquiry inquiry;
	
	/** Customer address that is part of price offer header. Default value is taken from inquiry address. */
	@Embedded
	@Valid
	private Address address = new Address();
	
	/** Customer phone number that is part of price offer header. Default value is taken from inquiry phone number. */
	@Size(max = LengthConstraints.CUSTOMER_PHONE_NUMBER)
	private String phoneNumber;
	
	/** Customer email that is part of price offer header. Default value is taken from inquiry email. */
	@Email
	@Size(max = ValidatorConstants.EMAIL_LENGTH)
	private String email;
		
	@OneToMany(fetch = FetchType.LAZY, mappedBy="priceOffer", cascade=CascadeType.REMOVE)
	@Valid
	private List<PriceOfferItem> priceOfferItemList;
	
	/** Note that may be printed in price offer for internal purposes (not visible to customer) */
	@Size(max=500)
	private String internalNote;

	@Column(nullable = false)
	private BigDecimal totalPriceWithoutVat = BigDecimal.ZERO;

	@Column(nullable = false)	
	private BigDecimal totalPriceWithVat = BigDecimal.ZERO;
	
	@Type(type=TypeDefsNames.JODA_DATE_TIME)
	@DateTimeFormat(pattern="dd.MM.yyyy")
	private DateTime date;

	public void calculatePrice() {
		totalPriceWithoutVat = BigDecimal.ZERO;
		totalPriceWithVat = BigDecimal.ZERO;
		for (PriceOfferItem priceOfferItem : priceOfferItemList) {
			totalPriceWithoutVat = totalPriceWithoutVat.add(priceOfferItem.getPriceWithoutVat());
			totalPriceWithVat = totalPriceWithVat.add(priceOfferItem.getPriceWithVat());
		}
	}
	
	public BigDecimal getTotalVat() {
		return totalPriceWithVat.subtract(totalPriceWithoutVat);
	}
	
	public BigDecimal getTotalPriceChipping() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceChipping() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceChipping()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceDisposal() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceDisposal() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceDisposal()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceTrimming() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceTrimming() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceTrimming()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceFelling() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceFelling() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceFelling()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceStumpsMilling() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceStumpsMilling() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceStumpsMilling()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceBinding() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceBinding() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceBinding()));
			}
		}
		return total;
	}
	
	public BigDecimal getTotalPriceOther() {
		Assert.notNull(priceOfferItemList);
		BigDecimal total = BigDecimal.ZERO;
		for (PriceOfferItem item : priceOfferItemList) {
			if (item.getPriceOther() != null) {
				total = total.add(item.getAmount().multiply(item.getPriceOther()));
			}
		}
		return total;
	}
	
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getVersion() {
		return version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public Inquiry getInquiry() {
		return inquiry;
	}

	public void setInquiry(Inquiry inquiry) {
		this.inquiry = inquiry;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getInternalNote() {
		return internalNote;
	}

	public void setInternalNote(String internalNote) {
		this.internalNote = internalNote;
	}

	public DateTime getDate() {
		return date;
	}

	public void setDate(DateTime date) {
		this.date = date;
	}

	public List<PriceOfferItem> getPriceOfferItemList() {
		return priceOfferItemList;
	}

	public void setPriceOfferItemList(List<PriceOfferItem> priceOfferItemList) {
		this.priceOfferItemList = priceOfferItemList;
	}

	public BigDecimal getTotalPriceWithoutVat() {
		return totalPriceWithoutVat;
	}

	public void setTotalPriceWithoutVat(BigDecimal totalPriceWithoutVat) {
		this.totalPriceWithoutVat = totalPriceWithoutVat;
	}

	public BigDecimal getTotalPriceWithVat() {
		return totalPriceWithVat;
	}

	public void setTotalPriceWithVat(BigDecimal totalPriceWithVat) {
		this.totalPriceWithVat = totalPriceWithVat;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) return true;
		if (obj == null) return false;
		if (getClass() != obj.getClass()) return false;
		PriceOffer other = (PriceOffer) obj;
		if (id == null) {
			if (other.id != null) return false;
		} else if (!id.equals(other.id)) return false;
		return true;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PriceOffer [id=");
		builder.append(id);
		builder.append(", version=");
		builder.append(version);
		builder.append(", inquiry=");
		builder.append(inquiry);
		builder.append(", address=");
		builder.append(address);
		builder.append(", phoneNumber=");
		builder.append(phoneNumber);
		builder.append(", email=");
		builder.append(email);
		builder.append(", priceOfferItemList=");
		builder.append(priceOfferItemList);
		builder.append(", internalNote=");
		builder.append(internalNote);
		builder.append(", totalPriceWithoutVat=");
		builder.append(totalPriceWithoutVat);
		builder.append(", totalPriceWithVat=");
		builder.append(totalPriceWithVat);
		builder.append(", date=");
		builder.append(date);
		builder.append("]");
		return builder.toString();
	}
	
	

}

src/main/webapp/WEB-INF/jsp/admin/inquiry/inquiryDetailPriceOffer.jsp
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/_include/taglibs.jsp" %>
<c:set var="selectedItem" value="inquiryList" scope="request"/>
<tiles:insertDefinition name=".layout.admin">
	<tiles:putAttribute name="title">Administrace - Kácení Šarapatka - detail poptávky - cenová nabídka</tiles:putAttribute>
	<tiles:putAttribute name="content">
		<div class="container">
			<h1 class="admin-theme">Detail poptávky - cenová nabídka</h1>
			<ul class="nav nav-tabs admin-menu">
			  <li><a href="<c:url value='/administrace/poptavky/detail-poptavky/${inquiryId}' />">Poptávka</a></li>
			  <li class="active"><a href="#">Cenová nabídka</a></li>
			</ul>
			<ui:message />
			<c:choose>
				<c:when test="${empty priceOffer}">
					<p class="alert alert-info">Cenová nabídka není vytvořená.</p>
					<div class="btns">
						<a href="<c:url value='/administrace/poptavky/detail-poptavky/${inquiryId}/nova-polozka-cenove-nabidky' />" class="btn btn-default">Vytvořit položku cenové nabídky</a>
						<a href="<c:url value='/administrace/poptavky/nahrat-cenovou-nabidku/${inquiryId}' />" class="btn btn-warning">Nahrát k poptávce cenovou nabídku</a>
					</div>
				</c:when>
				<c:otherwise>
					<p class="btns">
						<a href="<c:url value='/administrace/poptavky/detail-poptavky/${inquiryId}/nova-polozka-cenove-nabidky' />" class="btn btn-default">Vytvořit položku cenové nabídky</a>
						<a href="<c:url value='/administrace/poptavky/detail-poptavky/${inquiryId}/tisk-cenove-nabidky/${priceOffer.id}' />" class="btn btn-info" target="_blank">Vytisknout cenovou nabídku</a>
						<a href="<c:url value='/administrace/poptavky/detail-poptavky/${inquiryId}/upravit-cenovou-nabidku/${priceOffer.id}' />" class="btn btn-warning">Upravit doplňující údaje</a>
						<a href="<c:url value='/administrace/poptavky/detail-poptavky/${inquiryId}/smazat-cenovou-nabidku/${priceOffer.id}' />" class="btn btn-danger">Smazat cenovou nabídku</a>
					</p>
					<div class="row">
						<div class="col-sm-5">
							<dl>
								<dt>Adresa:</dt>
								<dd><c:out value="${!empty priceOffer.address && !empty priceOffer.address.name ? priceOffer.address.name : 'Jméno nezadáno'}" /></dd>
								<dd><c:out value="${!empty priceOffer.address && !empty priceOffer.address.street ? priceOffer.address.street : 'Ulice nazadána'}" /></dd>
								<dd><c:out value="${!empty priceOffer.address && !empty priceOffer.address.city ? priceOffer.address.city : 'Město nezadáno'}" /></dd>
								<dd><c:out value="${!empty priceOffer.address && !empty priceOffer.address.zip ? priceOffer.address.zip : 'PSČ nezadáno'}" /></dd>
							</dl>
							<dl class="dl-inline">	
								<dt>Telefon:</dt>
								<dd><c:out value="${priceOffer.phoneNumber}" /></dd>
								<dt>Email:</dt>
								<dd><c:out value="${priceOffer.email}" /></dd>
							</dl>
						</div>
						<div class="col-sm-7">
							<dl>
								<dt>Datum:</dt><dd><joda:format value="${priceOffer.date}" dateTimeZone="Europe/Prague" pattern="dd.MM.yyyy"/></dd>
								<c:if test="${!empty priceOffer.internalNote}">
									<dt>Poznámka:</dt>
									<dd><c:out value="${priceOffer.internalNote}" /></dd>
								</c:if>	
							</dl>
						</div>
					</div>	
					<jsp:include page="/WEB-INF/jsp/_include/priceOfferTable.jsp">
						<jsp:param value="true" name="edit"/>
						<jsp:param value="true" name="showVatRate"/>
					</jsp:include>
					<dl class="dl-inline">
						<dt>Cena celkem bez DPH:</dt><dd><f:formatNumber  minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceWithoutVat}"/></dd>
						<dt>Cena celkem s DPH:</dt><dd><f:formatNumber  minFractionDigits="2" maxFractionDigits="2" value="${priceOffer.totalPriceWithVat}"/></dd>
					</dl>
				</c:otherwise>
			</c:choose>
		</div>
    </tiles:putAttribute>
  </tiles:insertDefinition>

src/main/webapp/WEB-INF/jsp/admin/inquiry/inquiryList.jsp
<%@page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/WEB-INF/jsp/_include/taglibs.jsp" %>
<c:set var="selectedItem" value="inquiryList" scope="request"/>
<tiles:insertDefinition name=".layout.admin">
	<tiles:putAttribute name="title">Administrace - Kácení Šarapatka - přehled poptávek</tiles:putAttribute>
	<tiles:putAttribute name="content">
		<div class="container">
		<h1 class="admin-theme">Přehled poptávek</h1>
		<p>
			<a href="<c:url value='/administrace/poptavky/nahrat-cenovou-nabidku' />" class="btn btn-warning">Nahrát poptávku / cenovou nabídku</a>
			<a href="<c:url value='/administrace/poptavky/zadat-poptavku' />" class="btn btn-info">Zadat poptávku</a>
		</p>
		<form:form modelAttribute="inquiryFilter" cssClass="form-inline">
			<ui:message attrName="formErrorMessage" />
			<div class="errors">
				<form:errors path="*" element="p" />
			</div>
			<div class="form-group">
				<spring-ext:select path="inquiryState" cssClass="form-control">
				    <option value="">všechny</option>
	  				<c:forEach items="${inquiryStateEnumList}" var="inquiryState">
	  					<option value="${inquiryState}" <c:if test="${inquiryFilter.inquiryState == inquiryState}">selected="selected"</c:if>>
	  						<spring:message code="inquiryState.${inquiryState}" />
	  					</option>
	  				</c:forEach>
	  			</spring-ext:select>
  			</div>
  			<div class="form-group">
  				<spring-ext:input path="dateFrom"  maxlength="16" inputType="date" cssClass="form-control" forcePlaceholder="true" generateCssRelativeSize="false" includeErrors="false" />
  			</div>
  			<div class="form-group">
  				<spring-ext:input path="dateTo"  maxlength="16" inputType="date" cssClass="form-control" forcePlaceholder="true" generateCssRelativeSize="false" includeErrors="false"/>
  			</div>
  			<div class="form-group">
  				<spring-ext:input path="lastName" cssClass="form-control" forcePlaceholder="true" includeErrors="false"/>
  			</div>
			<div class="form-actions">
	    		<input type="submit" value="Vyhledat" name="filter" class="btn btn-primary"/>
				<input type="submit" value="Vymazat filter"  name="resetFilter" class="btn btn-default" />
			</div>	
		</form:form>
		<ui:message />
		<c:if test="${empty inquiryListPage || fn:length(inquiryListPage.content) == 0}" var="emptyInquiryList" />
		<c:choose>
			<c:when test="${emptyInquiryList}">
				<p class="alert alert-warning">Žádné poptávky nejsou k dispozici.</p>
			</c:when>
			<c:otherwise>
				<c:set var="inquiryList" value="${inquiryListPage.content}" />
				<ui:message />	
				<c:set var="paginationContext" value="${sessionScope['inquiryPaginationContext']}" />
				<table class="table table-bordered table-striped">
					<thead>
						<tr>
							<th>Datum</th>
							<th>Zákazník</th>
							<th>Zpráva</th>
							<th>Služby</th>
							<th>Poznámka</th>
							<th>&nbsp;</th>
							<th>&nbsp;</th>
						</tr>
					</thead>
					<tbody>
						<c:forEach items="${inquiryList}" var="inquiry">
							<tr>
								<td><a href="<c:url value='/administrace/poptavky/detail-poptavky/${inquiry.id}' />"><joda:format value="${inquiry.created}" pattern="dd.MM.yyyy HH:mm" dateTimeZone="Europe/Prague"/></a></td>
								<td>${inquiry.customer.name}</td>
								<td>${inquiry.message}</td>
								<td>${inquiry.adminSubject}</td>
								<td><c:out value="${inquiry.adminNote}" />
									<a href="<c:url value='/administrace/poptavky/upravit-poznamku-k-poptavce/${inquiry.id}'/>" title="Upravit poznámku"><i class="glyphicon glyphicon-pencil"><span class="sr-only">Upravit</span></i></a>
								</td>
								<td>
									<form action="<c:url value='/administrace/poptavky/zmenit-stav-poptavky' />" method="post">
										<input type="hidden" value="${inquiry.id}" name="inquiryId" />
										<select name="inquiryState" class="form-control input-sm">
											<c:forEach items="${inquiryStateEnumList}" var="inquiryState">
							  					<option value="${inquiryState}" <c:if test="${inquiry.state == inquiryState}">selected="selected"</c:if>>
							  						<spring:message code="inquiryState.${inquiryState}" />
							  					</option>
							  				</c:forEach>
							  			</select>
							  			<input type="submit" value="Změnit" class="btn btn-sm btn-default" />
									</form>
								</td>
								<td>
									<a href="<c:url value='/administrace/poptavky/smazat-poptavku/${inquiry.id}'/>" title="Smazat poptávku" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-remove"></i>&nbsp;Smazat</a>
								</td>		
							</tr>
						</c:forEach>
					</tbody>
				</table>
			</c:otherwise>
		</c:choose>
		<pagination:pages page="${inquiryListPage}" cssClass="pagination"  />
		</div>
    </tiles:putAttribute>
</tiles:insertDefinition>